

# returns hello world like home page 
GET https://contacts1-e96w.onrender.com/

# returns contacts stored in MongoDB
GET https://contacts1-e96w.onrender.com/contacts


# returns one contact by MongoDB id
# GET https://contacts1-e96w.onrender.com/contacts/CONTACT_ID


# https://youtu.be/nW7x_RbhIc8
# https://www.youtube.com/watch?v=nW7x_RbhIc8        



### Get all contacts
GET http://localhost:3000/contacts

### Open Swagger API documentation
GET http://localhost:3000/api-docs

### Get one contact from MongoDB
GET http://localhost:3000/contacts/CONTACT_ID