

# returns hello world like home page 
GET https://contacts1-e96w.onrender.com/

# returns all users
GET https://contacts1-e96w.onrender.com/users


# returns by id
GET https://contacts1-e96w.onrender.com/users/6a99802ee4fa31a2afcbc7e6